---
- hosts: all
  become: yes

  vars_files:
    - "./notify/discord.yml"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
      register: package_updates

    - name: Send discord message about package updated
      uri:
        url: "{{ url }}"
        method: POST
        body_format: json
        body: '{"content": "Package updates: {{ package_updates.packages | map(attribute="name") | list }}"}'
        headers:
          Content-Type: application/json
        status_code: 204