---
- hosts: all
  become: yes

  vars_files:
    - "./notify/discord.yml"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes

    - name: Send discord message when disk space is over 80%
      uri:
        url: "{{ url }}"
        method: POST
        body_format: json
        body: '{"content": "Package updates: {{ ansible_facts.packages | to_nice_yaml }}"}'
        headers:
          Content-Type: application/json
        status_code: 204