---
- hosts: all
  become: yes

  vars_files:
    - "./notify/discord.yml"

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
      register: package_upgrade_result

    - name: Send discord message with package upgrade information
      uri:
      url: "{{ url }}"
      method: POST
      body_format: json
      body: '{"content": "Packages upgraded on {{ inventory_hostname }}:\n{{ package_upgrade_result.stdout | to_nice_yaml }}"}'
      headers:
        Content-Type: application/json
      status_code: 204
      when: package_upgrade_result.changed
      ignore_errors: yes